name: fstar
description: 繁星课程表

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.5+35

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^3.0.10
  hive_flutter: ^1.0.0
  hive: ^2.0.4
  fluro: ^1.7.8
  flutter_easyloading: ^2.2.2
  awesome_dialog: ^2.0.0
  html: ^0.14.0+4
  image_picker: ^0.6.7+22
  install_plugin:
    git: https://github.com/hui-z/flutter_install_plugin.git
  flutter_neumorphic:
    git: https://github.com/Idean/Flutter-Neumorphic.git
  provider: ^5.0.0
  flutter_staggered_animations:
    git:
      url: https://github.com/josh-burton/flutter_staggered_animations.git
      ref: findAncestorWidgetOfExactType
  flutter_displaymode: ^0.1.1
  flutter_inappwebview: ^5.3.2
  device_info: ^2.0.0
  logger: ^1.0.0
  flutter_colorpicker: ^0.4.0
  flutter_material_color_picker: ^1.0.5
  tuple: ^2.0.0
  image_cropper: ^1.4.0
  path_provider: ^2.0.1
  url_launcher: ^6.0.3
  font_awesome_flutter: ^9.0.0
  pull_to_refresh: ^1.6.5
  flutter_rounded_date_picker: ^2.0.2
  flutter_screenutil: ^5.0.0
  just:
    git: https://github.com/DreamFever/just.git
  toggle_switch: ^0.1.9
  package_info: ^2.0.0
  #  permission_handler: ^5.0.1+2
  image_gallery_saver: ^1.6.7
  #  animations: ^1.1.2
  flutter_markdown: ^0.6.1
  excel:
    git:
      url: https://github.com/justkawal/excel.git
  shared_preferences: ^2.0.5
  crypto: ^3.0.1
  photo_view: ^0.11.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.11
  hive_generator: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
